#!/usr/bin/env bash
# Real pass/fail check for a built + converted install: BUILD is implied by
# getting here; this script checks LOAD, STT, TTS-only, and full S2S against
# meaningful output, not just "the process didn't crash". No benchmarking --
# see benchmark.sh for timing.
#
# This is the same bar used for new-hardware validation (docs/HARDWARE.md).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

GPU_TARGETS="${GPU_TARGETS:-gfx1201}"
BIN="build/hip-$GPU_TARGETS/bin/llama-voicechat"
RUNTIME="models/voicechat-q8/runtime"
CORPUS="research/corpus/VC01-short.wav"
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

echo "== BUILD =="
if [[ ! -x "$BIN" ]]; then
    echo "BUILD: FAIL -- $BIN not found or not executable" >&2
    exit 1
fi
echo "BUILD: PASS ($BIN)"

for f in "$RUNTIME/nemotron_voicechat_11b-stt-llm-Q8_0.gguf" \
         "$RUNTIME/mmproj-voicechat-perception-Q8_0.gguf" \
         "$RUNTIME/voicechat-tts-Q8_0.gguf"; do
    if [[ ! -f "$f" ]]; then
        echo "smoke-test.sh: missing converted artifact $f (run scripts/convert-q8.sh first)" >&2
        exit 1
    fi
done
if [[ ! -f "$CORPUS" ]]; then
    # The fixed corpus is deterministically self-generated by the model (see
    # research/scripts/harness/generate_corpus.sh) rather than committed as
    # binary WAV files (research/corpus/.gitignore excludes *.wav) -- a fresh
    # clone needs the built+converted runtime to produce it once.
    echo "smoke-test.sh: fixed corpus not found, generating it (research/scripts/harness/generate_corpus.sh)"
    research/scripts/harness/generate_corpus.sh
    if [[ ! -f "$CORPUS" ]]; then
        echo "smoke-test.sh: corpus generation did not produce $CORPUS" >&2
        exit 1
    fi
fi
EXPECTED_VC01="$(awk -F'\t' '$1 == "VC01" {print $3}' research/baselines/R9700-Q8-M1/corpus-manifest.tsv)"
if [[ -n "$EXPECTED_VC01" ]]; then
    ACTUAL_VC01="$(sha256sum "$CORPUS" | awk '{print $1}')"
    if [[ "$ACTUAL_VC01" != "$EXPECTED_VC01" ]]; then
        echo "smoke-test.sh: WARNING -- $CORPUS does not match the frozen R9700-Q8-M1" >&2
        echo "  corpus-manifest.tsv hash. Proceeding anyway; this is informational" >&2
        echo "  (a different pinned runtime or converted weights can legitimately" >&2
        echo "  change generated speech), not a hard failure." >&2
    fi
fi

export ROCR_VISIBLE_DEVICES="${ROCR_VISIBLE_DEVICES:-1}"
export GGML_CUDA_DISABLE_GRAPHS=1
export VC_NO_BARGE=1
export VC_FORCE_BOS=1

RESULT_FILE="$WORKDIR/result.json"
python3 - "$BIN" "$RUNTIME" "$CORPUS" "$WORKDIR" "$RESULT_FILE" <<'PYEOF'
import json, queue, subprocess, sys, threading, time, wave

bin_path, runtime, corpus, workdir, result_file = sys.argv[1:6]

def wav_seconds(path):
    with wave.open(path, "rb") as w:
        return w.getnframes() / w.getframerate()

cmd = [
    bin_path,
    "-m", f"{runtime}/nemotron_voicechat_11b-stt-llm-Q8_0.gguf",
    "--mmproj", f"{runtime}/mmproj-voicechat-perception-Q8_0.gguf",
    "--tts", f"{runtime}/voicechat-tts-Q8_0.gguf",
    "--serve", "--no-warmup", "--device", "ROCm0", "--split-mode", "none",
    "--gpu-layers", "all", "--temp", "0", "--seed", "42",
]
proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                         stderr=subprocess.PIPE, text=True, bufsize=1)

# stderr must be drained concurrently, or a busy log fills the pipe buffer
# and deadlocks against the stdout reader below (same reason
# research/scripts/harness/bench_r9700_q8.py's Service class uses a
# dedicated stderr thread).
stderr_lines = []
def _drain_stderr():
    for line in proc.stderr:
        stderr_lines.append(line)
threading.Thread(target=_drain_stderr, daemon=True).start()

def send(obj):
    proc.stdin.write(json.dumps(obj) + "\n")
    proc.stdin.flush()

def wait_for(kind, timeout=180):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        line = proc.stdout.readline()
        if not line:
            raise RuntimeError(f"process exited waiting for '{kind}': {''.join(stderr_lines[-100:])}")
        try:
            event = json.loads(line)
        except json.JSONDecodeError:
            continue
        if event.get("kind") == "error":
            raise RuntimeError(f"service error: {event}")
        if event.get("kind") == kind:
            return event
    raise TimeoutError(f"timed out waiting for '{kind}'")

results = {}
try:
    wait_for("ready")
    results["LOAD"] = "PASS"

    out_wav = f"{workdir}/s2s.wav"
    send({"cmd": "turn", "audio": corpus, "out": out_wav})
    turn = wait_for("turn_end")
    text = turn.get("text", "")
    results["STT"] = "PASS" if "paris" in text.lower() else f"FAIL (unexpected text: {text!r})"

    duration = wav_seconds(out_wav)
    results["S2S"] = "PASS" if duration > 0.5 else f"FAIL (output too short: {duration:.3f}s)"
finally:
    try:
        send({"cmd": "quit"})
        proc.wait(timeout=15)
    except Exception:
        proc.kill()

with open(result_file, "w") as f:
    json.dump(results, f)
PYEOF

echo "== LOAD/STT/S2S (--serve) =="
python3 -c "
import json, sys
with open('$RESULT_FILE') as f:
    results = json.load(f)
for k in ('LOAD', 'STT', 'S2S'):
    print(f'{k}: {results.get(k, \"FAIL (missing)\")}')
sys.exit(0 if all(v == 'PASS' for v in results.values()) else 1)
"

echo "== TTS-only (--say) =="
SAY_OUT="$WORKDIR/say.wav"
"$BIN" \
    -m "$RUNTIME/nemotron_voicechat_11b-stt-llm-Q8_0.gguf" \
    --mmproj "$RUNTIME/mmproj-voicechat-perception-Q8_0.gguf" \
    --tts "$RUNTIME/voicechat-tts-Q8_0.gguf" \
    --no-warmup --device ROCm0 --split-mode none --gpu-layers all \
    --say "This is a smoke test." --tts-out "$SAY_OUT" >/dev/null 2>"$WORKDIR/say.stderr.txt"

SAY_SECONDS="$(python3 -c "import wave,sys; print(wave.open(sys.argv[1]).getnframes()/wave.open(sys.argv[1]).getframerate())" "$SAY_OUT" 2>/dev/null || echo 0)"
if awk "BEGIN{exit !($SAY_SECONDS > 0.3)}"; then
    echo "TTS-only: PASS (${SAY_SECONDS}s)"
else
    echo "TTS-only: FAIL (output too short or missing: ${SAY_SECONDS}s)" >&2
    cat "$WORKDIR/say.stderr.txt" >&2
    exit 1
fi

echo "smoke-test.sh: all checks passed"
